---
name: FPGA - Chisel CI

on:
  pull_request:
    branches: [master]
    paths:
      - 'fpga/**'

jobs:
  tests:
    runs-on: [self-hosted, ubuntu-18-04]
    defaults:
      run:
        working-directory: ./fpga

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11

      - name: Check formatting
        run: sbt scalafmtCheck

      - name: Run tests
        run: sbt test
